### ISSUE TITLE
ModuleNotFoundError: No module named 'train_hnet'

### ISSUE THREAD

**Issue by springGUOHUO** [sharathadavanne/doa-net#2]
Thank you very much for your source code，I ran the code with the following error：
Traceback (most recent call last):
  File "train_doanet.py", line 23, in <module>
    from train_hnet import HNetGRU
ModuleNotFoundError: No module named 'train_hnet'

I can't find the train_hnet and HNetGRU, if you konw what happen, please help me, thank you!

**Comment by sharathadavanne** [comment]
Hi @springGUOHUO thanks for raising this issue. I noticed that I have missed out on describing this part. I will update the readme accordingly soon.

1. Please clone the Hungarian-net repo from here - https://github.com/sharathadavanne/hungarian-net 
2. Update the path of this repo in [line 19](https://github.com/sharathadavanne/doa-net/blob/c9815e21bf04880a41600851c3e48bb5fd916bfc/train_doanet.py#L19)

It should work fine thereafter.

Also, let me know if there is something else that you couldn't find in Readme with regard to running the code, I will update them accordingly :)

**Comment by springGUOHUO** [comment]
> Hi @springGUOHUO thanks for raising this issue. I noticed that I have missed out on describing this part. I will update the readme accordingly soon.
> 
> 1. Please clone the Hungarian-net repo from here - https://github.com/sharathadavanne/hungarian-net
> 2. Update the path of this repo in [line 19](https://github.com/sharathadavanne/doa-net/blob/c9815e21bf04880a41600851c3e48bb5fd916bfc/train_doanet.py#L19)
> 
> It should work fine thereafter.
> 
> Also, let me know if there is something else that you couldn't find in Readme with regard to running the code, I will update them accordingly :)

thanks a lot. Now it looks fine. :)
